# Generated by Django 5.0.7 on 2024-08-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mzuri', '0002_alter_buy_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_product',
            name='description',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
