# Generated by Django 5.0.7 on 2024-08-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mzuri', '0003_alter_buy_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_product',
            name='title',
            field=models.CharField(max_length=15),
        ),
    ]
