# Generated by Django 5.0.7 on 2024-08-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mzuri', '0004_alter_buy_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_product',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
