# Generated by Django 5.0.7 on 2024-08-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mzuri', '0005_alter_buy_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_product',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
