# Generated by Django 5.0.7 on 2024-08-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mzuri', '0006_alter_buy_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Mzuri_uploads/'),
        ),
    ]
