# Generated by Django 5.0.7 on 2024-08-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mzuri', '0007_alter_buy_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_product',
            name='image',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
    ]
