# Generated by Django 5.0.7 on 2024-08-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mzuri', '0010_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
