# Generated by Django 5.0.7 on 2024-11-24 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mzuri', '0013_alter_buyproduct_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=45)),
                ('company_picture', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPagePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/')),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_pictures', to='Mzuri.portfoliosection')),
            ],
        ),
    ]
